language: node_js

deploy:
  provider: firebase
  token:
    secure: i8PXknFrYXbp9Duf0UmvJyjbgGY7W22ZWTko+H+Nxs2feHVDoLllYemtE4LpziQWcTtySJVcNMW0ZJvzLIIUBehh3ogBoLylvocCqtSAPEbRTzd5DPHXMbR5pmQociOGzgUbCT0qw3bSHq4nyezN8KwU1kLg1ZtB/Zuk2Mm724wRB4+OZoTdKaFrSBH9dJ1YMURfl5+1cLZHtNye692EzogALCvhs9vjC9ItnKRtV08RE2tP0EPbe73eeIzBcStlLBjYkZn0/SF8ZnvnkQtBMggQtaGHBp4fbaSVeIwok0ni/xiZUhimNqGathZPRkyIHiTWdpYKqE+jA3sW5OWjNZWJIzM/iY6G1YpCKQsd/xQnjxU4XEm1HPC9w3jSyhAVXeDkoIZDDHTRyStv+63O/gQtJ6U68fgMjo9rK4VLhfEb5feOeixyn7ppY36f9A61rj60cjYCeeYpCe2q5JFDhai/Vb5D8dBC9GvfxTcC/owYsxXeOTE6VHwMUc+AAB0FEEZHrP6PREsvM09FyAQjeKf2/bGUS1AxzSziQuj5Rlcc/9FDPARIyuWu2CEVhmU1mBsyeJ9BG87Rp+flGvp9i2lsMaxZH8dpWMYWSVYPaQMIXNt9QoR9YRvZkdUqN9W1zLusI71JEKSvqnQukXYlMB3sI8Zt4rxCPl5djku6T0k=
  project: techheaven-general